const {chromium}=require('/usr/local/lib/python3.10/dist-packages/playwright/driver/package');
const fs=require('fs'),assert=require('assert'),{isDeepStrictEqual}=require('util');const O='/tmp/repair021-second',B='http://census-web:8080';fs.mkdirSync(O,{recursive:true});
const base='/table/ACSDT5Y2018.B01001?g=040XX00US10,050XX00US10$0500000&tp=true';
(async()=>{const browser=await chromium.launch({executablePath:'/opt/chrome-linux64/chrome',chromiumSandbox:true,headless:true});const c=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});await c.tracing.start({screenshots:true,snapshots:true});await c.route('**/*',r=>r.request().url().startsWith(B+'/')?r.continue():r.abort());const p=await c.newPage();p.setDefaultTimeout(15000);const checks=[],errors=[];p.on('pageerror',e=>errors.push(String(e)));
function check(name,pass,extra={}){checks.push({name,pass:!!pass,...extra});assert(pass,name)}
async function opened(path=base){await p.goto(B+path);await p.waitForSelector('#grid table');}
async function count(n){await p.waitForFunction(n=>document.querySelectorAll('#grid [data-group]').length===n,n);}
async function filter(op,val){await p.click('#customFilter');await p.selectOption('#filterVariable','B01001_001E');await p.selectOption('#filterOperator',op);await p.fill('#filterValue',val);await p.click('#applyFilter');}
async function clear(){await p.click('#customFilter');await p.click('#clearFilters');}
async function download(fmt,name){await p.click('#download');await p.check(`[name=format][value=${fmt}]`);const wait=p.waitForEvent('download');await p.click('#confirmDownload');const d=await wait;await d.saveAs(O+'/'+name+'.'+fmt);}
async function state(){return await p.evaluate(()=>JSON.parse(JSON.stringify(S)));}
try{
 await opened();await count(4);
 for(const [op,n] of [['ge',1],['gt',0],['le',4],['lt',3],['eq',1],['ne',3]]){await filter(op,'949495');await count(n);await clear();await count(4);check('operator '+op,true);}
 await filter('ge','0');await p.click('[data-sort="B01001_001E"]');await p.click('#columns');await p.uncheck('#modalBody input[value="B01001_003E"]');await p.click('#applyColumns');
 fs.writeFileSync(O+'/custom-dom.json',JSON.stringify(await p.locator('#grid tr').evaluateAll(rs=>rs.map(r=>[...r.cells].map(c=>c.innerText))),null,2));fs.writeFileSync(O+'/custom-state.json',JSON.stringify(await state(),null,2));
 for(const fmt of ['csv','xlsx','zip'])await download(fmt,'custom');check('all three formats downloaded',true);await p.screenshot({path:O+'/custom-table.png'});
 const before=await state();await p.click('#showMap');await p.waitForSelector('#map path');await p.selectOption('#mapVariable','B01001_002E');await p.waitForSelector('#map path');await p.selectOption('#year','2019');await p.waitForFunction(()=>result?.year===2019);let s=await state();check('year resets customizations preserves geographies',s.geo.join()===before.geo.join()&&!s.filters.length&&!s.hidden.length&&s.sort==='name'&&!new URL(p.url()).searchParams.has('mapVariable'));
 await p.selectOption('#product','acs1');await p.waitForFunction(()=>result?.product==='acs1');s=await state();check('product change preserves geographies',s.geo.join()===before.geo.join());await p.click('#showTable');await p.uncheck('#moe');await p.click('#transpose');s=await state();check('transpose and MOE preserve geography and population',s.geo.join()===before.geo.join()&&s.product==='acs1'&&!s.moe&&!s.tp);
 await opened();await filter('ge','100000');const filtered=await state();await p.click('#showMap');await p.waitForSelector('#map path');await p.click('#mapSelection');await p.waitForSelector('#map path[data-geo="10001"]');await p.locator('#map path[data-geo="10001"]').click({force:true});await p.click('#mapAction');await p.waitForFunction(()=>result?.rows.length===3);s=await state();check('map removes one county from all counties preserving filter',!s.geo.includes('10*')&&!s.geo.includes('10001')&&s.filters.length===1);await p.reload();await p.waitForFunction(()=>result?.rows.length===3);check('map selection and filters survive reload',(await state()).filters[0].value==='100000');await download('csv','map-removed');
 // Selection mode is an editing tool, not part of the query URL; enable explicitly after reload.
 if(!(await p.getAttribute('#mapSelection','aria-pressed')==='true'))await p.click('#mapSelection');await p.waitForSelector('#map path[data-geo="10001"]');await p.locator('#map path[data-geo="10001"]').click({force:true});await p.click('#mapAction');await p.waitForFunction(()=>result?.rows.length===4);check('map add-back restores geography', (await state()).geo.includes('10001'));await p.screenshot({path:O+'/map-restored.png'});
 await p.click('#mapSelection');await filter('gt','1e12');await p.waitForFunction(()=>document.querySelector('#map .empty'));check('empty map clears legend hover and action',await p.locator('#legend').innerText()===''&&await p.locator('#mapHover').innerText()===''&&await p.locator('#mapAction').isHidden());await clear();
 await opened();await filter('gt','1e5');const href=p.url(),saved=await state();await p.reload();await p.waitForSelector('#grid table');check('scientific threshold restores',isDeepStrictEqual((await state()).filters,saved.filters));await p.click('#transpose');await p.goBack();await p.waitForSelector('#grid table');check('back restores transpose',(await state()).tp===true);await p.goForward();await p.waitForSelector('#grid table');check('forward restores transpose',(await state()).tp===false);
 const tab=await c.newPage();await tab.goto(href);await tab.waitForSelector('#grid table');const ts=await tab.evaluate(()=>JSON.parse(JSON.stringify(S)));check('copied URL restores independent tab',ts.tp===true&&ts.filters[0].value==='1e5');await tab.close();
 await opened();await filter('ge','1');await p.fill('#search','B19013');await p.locator('#searchForm button[type=submit]').click();await p.waitForFunction(()=>result?.table.id==='B19013');check('search keeps geographies and announces reset',(await state()).geo.length===2&&!(await state()).filters.length&&(await p.locator('#status').innerText()).includes('cleared'));
 await p.fill('#search','B01001');await p.locator('#suggestions [data-table="B01001"]').click();await p.waitForFunction(()=>result?.table.id==='B01001');check('suggestion visibly announces geography reset',!(await state()).geo.length&&(await p.locator('#status').innerText()).includes('geography filters'));
 await p.locator('details').last().locator('summary').click();await p.click('[data-topic=Housing]');await p.waitForSelector('.result');check('topic entry resets table scope',!(await state()).table&&!(await state()).filters.length);
 for(const encoded of ['B01001_001E~(NaNne)','B01001_001E~(1bogus)','B99999_001E~(1gt)']){await p.goto(B+base+'&tableFilters='+encodeURIComponent(encoded));await p.waitForFunction(()=>/Invalid/.test(document.querySelector('#status').textContent));check('invalid URL visibly rejected '+encoded,await p.locator('#tablePanel').isHidden());}
 for(const bad of [{variable:'B01001_001E',op:'ne',value:'NaN'},{variable:'B01001_001E',op:'bogus',value:'1'},{variable:'B99999_001E',op:'gt',value:'1'}])for(const endpoint of ['/api/table','/download']){const r=await c.request.get(B+endpoint,{params:{year:2018,product:'acs5',table:'B01001',geo:'10*',filters:JSON.stringify([bad])}});check('HTTP rejects invalid customizations '+endpoint+' '+bad.op,r.status()===400);}
 await opened();let release,entered;const waitEntered=new Promise(r=>entered=r);const hold=new Promise(r=>release=r);await p.route('**/api/table?*',async route=>{if(route.request().url().includes('year=2019')){entered();await hold;}await route.continue().catch(()=>{});});await p.selectOption('#year','2019');await waitEntered;await p.selectOption('#year','2017');await p.waitForFunction(()=>result?.year===2017);release();await p.waitForTimeout(400);check('delayed old query cannot replace latest year',await p.evaluate(()=>result.year===2017));await p.unroute('**/api/table?*');
 let release2,entered2;const hit2=new Promise(r=>entered2=r),hold2=new Promise(r=>release2=r);await p.route('**/api/table?*',async route=>{entered2();await hold2;await route.continue().catch(()=>{});});await p.selectOption('#year','2019');await hit2;await p.evaluate(()=>{history.pushState(null,'','/');dispatchEvent(new PopStateEvent('popstate'));});release2();await p.waitForTimeout(400);check('leaving workspace invalidates pending response',await p.evaluate(()=>result===null&&document.querySelector('#tablePanel').hidden&&!document.querySelector('#portal').hidden));await p.unroute('**/api/table?*');
 await opened('/table/ACSDT5Y2018.B01001?g=040XX00US10,050XX00US10$0500000,040XX00US48,050XX00US48$0500000&tp=true');await p.waitForSelector('#grid table');check('mixed coverage remains explicit',(await p.locator('#availability').innerText()).includes('259'));await download('xlsx','partial');await download('zip','partial');
 await p.goto(B+'/table/ACSDT5Y2018.B01001?g=040XX00US48,050XX00US48$0500000&tp=true');await p.waitForSelector('#grid .empty');check('no-data geography remains selected',(await state()).geo.join()==='48,48*'&&await p.locator('#grid .empty').count()===1);await p.click('#showMap');await p.waitForSelector('#map path');check('no-data map no stale numeric legend',(await p.locator('#legend').innerText()).includes('No numerical values'));await p.screenshot({path:O+'/no-data-map.png'});
 check('no uncaught JavaScript errors',errors.length===0,{errors});
}catch(e){checks.push({name:'execution',pass:false,error:String(e),stack:e.stack});await p.screenshot({path:O+'/failure.png'}).catch(()=>{});console.error(e);process.exitCode=1;}finally{fs.writeFileSync(O+'/checks.json',JSON.stringify({checks,errors},null,2));await c.tracing.stop({path:O+'/trace.zip'});await browser.close();console.log(JSON.stringify(checks));}})();
