'use strict';
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let stateNotice='',mapSelection=false,mapFocus=null;let mapGeneration=0;let S, geographies=[], result=null, generation=0, suggestionGeneration=0, mapZoom=1, mapOffset=[0,0], shapes=null;
const defaults=()=>({year:2018,product:'acs5',geo:[],q:'',table:'',tp:false,moe:true,filters:[],hidden:[],hiddenGeo:[],sort:'name',direction:'asc',view:'table',mapVariable:''});
function decode(){const p=new URLSearchParams(location.search),s=defaults(),m=location.pathname.match(/ACSDT([15])Y(\d+)\.([BC]\d+[A-Z]{0,3})/);if(m){s.product='acs'+m[1];s.year=+m[2];s.table=m[3];}s.year=+(p.get('y')||s.year);if(p.has('d'))s.product=p.get('d').includes('1-Year')?'acs1':p.get('d').includes('5-Year')?'acs5':p.get('d');s.q=p.get('q')||'';s.tp=p.get('tp')==='true';s.moe=p.get('moe')!=='false';s.view=p.get('view')||'table';s.sort=p.get('sort')||'name';s.direction=p.get('direction')||'asc';s.hidden=(p.get('hidden')||'').split(',').filter(Boolean);s.hiddenGeo=(p.get('hiddenGeo')||'').split(',').filter(Boolean);s.mapVariable=p.get('mapVariable')||'';
 let inheritedLevel='';for(const g of (p.get('g')||'').split(',')){let a;if(g.startsWith('040XX00US'))inheritedLevel='040';if(g.startsWith('050XX00US'))inheritedLevel='050';if((a=g.match(/^(\d{2})\$0500000$/))){s.geo.push(a[1]+'*');continue;}if((a=g.match(/^(\d{5})$/))&&inheritedLevel==='050'){s.geo.push(a[1]);continue;}if((a=g.match(/^(\d{2})$/))&&inheritedLevel==='040'){s.geo.push(a[1]);continue;}if((a=g.match(/^040XX00US(\d{2})$/)))s.geo.push(a[1]);else if((a=g.match(/^050XX00US(\d{2})\$0500000$/)))s.geo.push(a[1]+'*');else if((a=g.match(/^050XX00US(\d{5})$/)))s.geo.push(a[1]);else if(g)throw Error('Unsupported geography selection: '+g);}
 for(const key of ['tp','moe'])if(p.has(key)&&!['true','false'].includes(p.get(key)))throw Error('Invalid '+key+' setting');
 if(!['asc','desc'].includes(s.direction)||!['map','table'].includes(s.view))throw Error('Invalid sort direction or view');
 const encoded=p.get('tableFilters')||'';for(const f of encoded?encoded.split(','):[]){const a=f.match(/^([BC]\d+[A-Z]{0,3}_\d+E)~\(([+-]?(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][+-]?\d+)?)(ge|gt|le|lt|eq|ne)\)$/);if(!a||!Number.isFinite(Number(a[2])))throw Error('Invalid table filter: use an available variable, a finite number and a supported comparison.');s.filters.push({variable:a[1],value:a[2],op:a[3]});}if(s.filters.length>30)throw Error('Expected at most 30 table filters');return s;}

function url(){const p=new URLSearchParams({y:String(S.year),d:`ACS ${S.product==='acs5'?'5':'1'}-Year Estimates Detailed Tables`});if(S.geo.length)p.set('g',S.geo.map(g=>g.endsWith('*')?'050XX00US'+g.slice(0,2)+'$0500000':(g.length===2?'040XX00US':'050XX00US')+g).join(','));if(S.q)p.set('q',S.q);if(S.tp)p.set('tp','true');if(!S.moe)p.set('moe','false');if(S.view==='map')p.set('view','map');if(S.filters.length)p.set('tableFilters',S.filters.map(f=>`${f.variable}~(${f.value}${f.op})`).join(','));for(const k of ['hidden','hiddenGeo'])if(S[k].length)p.set(k,S[k].join(','));if(S.sort!=='name')p.set('sort',S.sort);if(S.direction==='desc')p.set('direction','desc');if(S.mapVariable)p.set('mapVariable',S.mapVariable);return(S.table?`/table/ACSDT${S.product==='acs5'?5:1}Y${S.year}.${S.table}`:'/advanced')+'?'+p;}
function save(){history.pushState(null,'',url());}function error(e){$('status').textContent=e.message||e;}
async function fetchJSON(path){const r=await fetch(path),d=await r.json();if(!r.ok)throw Error(d.error||'Request failed');return d;}
function apiParams(){return new URLSearchParams({year:S.year,product:S.product,table:S.table,geo:S.geo.join(','),filters:JSON.stringify(S.filters),hidden:S.hidden.join(','),hiddenGeo:S.hiddenGeo.join(','),tp:S.tp,moe:S.moe,sort:S.sort,direction:S.direction});}
function resetTable(notice='Table-specific filters, sorting, hidden items and map variable were cleared; geographies retained.'){S.filters=[];S.hidden=[];S.hiddenGeo=[];S.sort='name';S.direction='asc';S.mapVariable='';stateNotice=notice;}
function bind(id,fn){$(id).onclick=fn;}
function change(fn,load=true){fn();save();if(load)refresh();else{if(stateNotice){$('status').textContent=stateNotice;stateNotice='';}render();}}
function clearMap(){mapFocus=null;shapes=null;$('mapHover').textContent='';$('legend').textContent='';$('mapAction').hidden=true;$('map').replaceChildren();}
function chip(label,action){return `<span class="chip">${esc(label)}<button data-remove="${esc(action)}" aria-label="Remove ${esc(label)}">×</button></span>`;}
function renderChips(){let html=chip(`${S.year}: ACS ${S.product==='acs5'?5:1}-Year`,'release');for(const g of S.geo){const v=geographies.find(x=>x.id===g.replace('*',''));html+=chip(g.endsWith('*')?'All counties within '+(v?.name||g):v?.name||g,g);}$('chips').innerHTML=html;$('chips').querySelectorAll('button').forEach(b=>b.onclick=()=>change(()=>{if(b.dataset.remove==='release'){S.year=2018;S.product='acs5';resetTable();}else S.geo=S.geo.filter(g=>g!==b.dataset.remove);}));}
function choices(){const st=$('state').value,gs=geographies.filter(g=>g.state===st&&g.level==='county');$('geoChoices').innerHTML=st?[{id:st,name:geographies.find(g=>g.id===st)?.name||st},{id:st+'*',name:'All counties within '+(geographies.find(g=>g.id===st)?.name||st)},...gs].map(g=>`<label><input type="checkbox" value="${g.id}" ${S.geo.includes(g.id)?'checked':''}>${esc(g.name)}</label>`).join(''):'';}
async function refresh(){const gen=++generation;++mapGeneration;clearMap();++suggestionGeneration;result=null;$('status').textContent='Loading selected release…';$('tablePanel').hidden=true;$('results').innerHTML='';$('year').value=S.year;$('product').value=S.product;$('search').value=S.q;$('suggestions').innerHTML='';
 try{const g=await fetchJSON('/api/geographies?year='+S.year);if(gen!==generation)return;geographies=g;const st=$('state').value||S.geo[0]?.slice(0,2)||'';$('state').innerHTML='<option value="">Select a state</option>'+g.filter(x=>x.level==='state').map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('');$('state').value=st;choices();renderChips();
 if(S.table){const d=await fetchJSON('/api/table?'+apiParams());if(gen!==generation)return;if(S.mapVariable&&!d.variables.some(v=>v.id===S.mapVariable))throw Error('Invalid map variable');result=d;$('status').textContent=stateNotice;stateNotice='';render();}
 else{const d=await fetchJSON('/api/catalog?'+new URLSearchParams({year:S.year,product:S.product,q:S.q,geo:S.geo.join(',')}));if(gen!==generation)return;$('status').textContent=stateNotice;stateNotice='';$('results').innerHTML=`<h1>${d.length} table results</h1><p class="muted">${S.year}: ACS ${S.product==='acs5'?5:1}-Year Estimates Detailed Tables</p>`+d.map(t=>`<article class="result"><div class="eyebrow">${esc(t.id)} · ${esc(t.coverage.message)}</div><h2><button data-table="${t.id}">${esc(t.title)}</button></h2></article>`).join('');$('results').querySelectorAll('[data-table]').forEach(b=>b.onclick=()=>change(()=>{S.table=b.dataset.table;resetTable();}));}
 }catch(e){if(gen===generation){result=null;error(e);}}}
function mapEstimate(r){const v=r?.values[S.mapVariable];return v?.ea?null:v?.estimate;}
function value(cell,k='estimate'){if(!cell)return '—';const a=cell[k==='estimate'?'ea':'ma'];if(a)return a;let n=cell[k];if(n==null)return '—';return (k==='moe'?'±':'')+Number(n).toLocaleString('en-US',{maximumFractionDigits:6});}
function compareNames(a,b){const key=x=>x.normalize('NFD').replace(/\p{M}/gu,'').toLowerCase();a=key(a);b=key(b);return a<b?-1:a>b?1:0;}
function visibleRows(){let rows=result.rows.filter(r=>r.available&&!S.hiddenGeo.includes(r.id));for(const f of S.filters){rows=rows.filter(r=>{const x=r.values[f.variable]?.estimate,v=Number(f.value);if(x==null||r.values[f.variable]?.ea)return false;return {ge:x>=v,gt:x>v,le:x<=v,lt:x<v,eq:x===v,ne:x!==v}[f.op];});}rows.sort((a,b)=>{let c;if(S.sort==='name')c=a.level!==b.level?(a.level==='state'?-1:1):compareNames(a.name,b.name);else{const x=a.values[S.sort]?.ea?null:a.values[S.sort]?.estimate,y=b.values[S.sort]?.ea?null:b.values[S.sort]?.estimate;c=(x??-Infinity)-(y??-Infinity);}return S.direction==='asc'?c:-c;});return rows;}
function render(){if(!result)return;$('tablePanel').hidden=false;$('results').innerHTML='';$('release').textContent=`${S.year}: ACS ${S.product==='acs5'?'5':'1'}-Year Estimates Detailed Tables · ${S.product==='acs5'?S.year-4+'–'+S.year:S.year}`;$('title').textContent=result.table.id+' | '+result.table.title;$('universe').textContent='Universe: '+result.table.universe;$('moe').checked=S.moe;$('transpose').setAttribute('aria-pressed',S.tp);$('filterChips').innerHTML=S.filters.map((f,i)=>chip(`${f.variable} ${f.op} ${f.value}`,i)).join('');$('filterChips').querySelectorAll('button').forEach(b=>b.onclick=()=>change(()=>S.filters.splice(+b.dataset.remove,1),false));
 const rows=visibleRows(),vars=result.variables.filter(v=>!S.hidden.includes(v.id));$('availability').textContent=result.coverage.message+' '+rows.length+' geographies shown after table customizations.';
 const keys=S.moe?['estimate','moe']:['estimate'];let h='<table><thead><tr>';
 if(S.tp){h+='<th><button id="sortName">Label (Grouping)</button></th>';for(const v of vars)h+=`<th title="${esc(v.id)}"><button data-sort="${v.id}">${esc(v.label.replace('Estimate!!',''))}</button></th>`;h+='</tr></thead><tbody>';for(const r of rows){h+=`<tr class="geo-group" data-group="${r.id}"><td>${esc(r.name)}</td>`+vars.map(()=>'<td></td>').join('')+'</tr>';for(const k of keys){h+=`<tr data-geo="${r.id}" data-row-kind="${k}"><td class="measure-label">${k==='moe'?'Margin of Error':'Estimate'}</td>`;for(const v of vars)h+=`<td class="${k==='moe'?'moe':''}" data-variable="${v.id}" data-kind="${k}">${esc(value(r.values[v.id],k))}</td>`;h+='</tr>';}}}
 else{h+='<th>Label (Grouping)</th>';for(const r of rows)for(const k of keys)h+=`<th>${esc(r.name)}<br>${k==='moe'?'Margin of Error':'Estimate'}</th>`;h+='</tr></thead><tbody>';for(const v of vars){const parts=v.label.replace('Estimate!!','').split('!!');h+=`<tr data-variable="${v.id}"><td style="padding-left:${12+Math.max(0,parts.length-1)*12}px"><button data-definition="${v.id}">${esc(parts.at(-1))}</button></td>`;for(const r of rows)for(const k of keys)h+=`<td data-geo="${r.id}" data-kind="${k}" class="${k==='moe'?'moe':''}">${esc(value(r.values[v.id],k))}</td>`;h+='</tr>';}}
 h+='</tbody></table>';$('grid').innerHTML=rows.length?h:'<div class="empty">No rows to display. Adjust your geographies or table filters.</div>';$('grid').querySelectorAll('[data-sort]').forEach(b=>b.onclick=()=>sort(b.dataset.sort));if($('sortName'))bind('sortName',()=>sort('name'));$('grid').querySelectorAll('[data-definition]').forEach(b=>b.onclick=()=>{const v=result.variables.find(v=>v.id===b.dataset.definition);modal(`<h2>${esc(v.id)}</h2><p>${esc(v.label)}</p><p>Universe: ${esc(result.table.universe)}</p><p>Unit: ${esc(v.unit)}. Estimate and 90% margin of error are separate values.</p>`);});$('footnotes').textContent='Source: U.S. Census Bureau, American Community Survey. Official Summary Files and saved official table exports; source-specific annotations are preserved. Estimates and margins of error are not interchangeable. See Help for coverage and precision.';$('grid').hidden=S.view==='map';$('mapPanel').hidden=S.view!=='map';if(S.view==='map')renderMap();else{++mapGeneration;clearMap();}}
function sort(v){change(()=>{S.direction=S.sort===v&&S.direction==='asc'?'desc':'asc';S.sort=v;},false);}
function modal(html){$('modalBody').innerHTML=html;$('modal').showModal();}
async function renderMap(){if(!result)return;const gen=generation,mapGen=++mapGeneration;clearMap();const vars=result.variables;$('mapVariable').innerHTML=vars.map(v=>`<option value="${v.id}">${esc(v.label.replace('Estimate!!',''))}</option>`).join('');if(!vars.some(v=>v.id===S.mapVariable))S.mapVariable=vars[0]?.id||'';$('mapVariable').value=S.mapVariable;
 try{const data=await fetchJSON('/boundaries/'+S.year+'.json');if(gen!==generation||mapGen!==mapGeneration||S.view!=='map')return;const rows=result.rows,byId=new Map(rows.map(r=>[r.id,r]));const states=new Set(S.geo.map(g=>g.slice(0,2)));const visible=new Set(visibleRows().map(r=>r.id));let fs=data.features.filter(f=>mapSelection?states.has(f.properties.GEOID.slice(0,2))&&f.properties.GEOID.length===5:byId.has(f.properties.GEOID)&&(!byId.get(f.properties.GEOID).available||visible.has(f.properties.GEOID)));for(const f of fs)if(!byId.has(f.properties.GEOID)){const g=geographies.find(g=>g.id===f.properties.GEOID);byId.set(f.properties.GEOID,{...g,values:{}});}if(fs.some(f=>f.properties.GEOID.length===5))fs=fs.filter(f=>f.properties.GEOID.length===5);shapes=fs;const pts=[];function points(c){if(typeof c[0]==='number')pts.push(c);else c.forEach(points);}fs.forEach(f=>points(f.geometry.coordinates));if(!pts.length){$('legend').innerHTML='';$('mapAction').hidden=true;$('map').innerHTML='<p class="empty">No archived data in the selected map scope.</p>';return;}
 const xmin=pts.reduce((a,p)=>Math.min(a,p[0]),Infinity),xmax=pts.reduce((a,p)=>Math.max(a,p[0]),-Infinity),ymin=pts.reduce((a,p)=>Math.min(a,p[1]),Infinity),ymax=pts.reduce((a,p)=>Math.max(a,p[1]),-Infinity),cos=Math.cos((ymin+ymax)/2*Math.PI/180),scale=Math.min(900/((xmax-xmin)*cos),410/(ymax-ymin));const xy=p=>[(p[0]-(xmin+xmax)/2)*cos*scale+480,235-(p[1]-(ymin+ymax)/2)*scale];
 const vals=fs.map(f=>mapEstimate(byId.get(f.properties.GEOID))).filter(x=>x!=null),min=Math.min(...vals),max=Math.max(...vals),colors=['#e3eef6','#b5d4e9','#79b3d5','#3d8dbc','#125b90'];function color(v){return v==null?'#ddd':colors[Math.min(4,Math.floor(5*(v-min)/(max-min||1)))];}
 function ring(c){return c.map((p,i)=>(i?'L':'M')+xy(p).join(',')).join(' ')+'Z';}function shape(f){const polys=f.geometry.type==='Polygon'?[f.geometry.coordinates]:f.geometry.coordinates;return polys.map(p=>p.map(ring).join(' ')).join(' ');}
 $('map').innerHTML='<svg viewBox="0 0 960 470" aria-label="County boundaries and estimates"><g id="mapShapes">'+fs.map(f=>`<path data-geo="${f.properties.GEOID}" fill="${color(mapEstimate(byId.get(f.properties.GEOID)))}" fill-rule="evenodd" d="${shape(f)}"><title>${esc(byId.get(f.properties.GEOID).name)}</title></path>`).join('')+'</g></svg>';$('map').querySelectorAll('path').forEach(el=>{const r=byId.get(el.dataset.geo);el.onpointerenter=()=>{$('mapHover').textContent=r.name+' · '+value(r.values[S.mapVariable]);};el.onclick=()=>{$('map').querySelectorAll('path').forEach(p=>p.classList.remove('selected'));el.classList.add('selected');mapFocus=r;$('mapHover').textContent=r.name+' · '+value(r.values[S.mapVariable]);$('mapAction').hidden=!mapSelection;$('mapAction').textContent=mapContains(r.id)?'Deselect geography':'Select geography';};});$('legend').innerHTML=(vals.length?colors.map((c,i)=>`<span><i style="background:${c}"></i>${Math.round(min+(max-min)*i/5).toLocaleString()}–${Math.round(min+(max-min)*(i+1)/5).toLocaleString()}</span>`).join(''):'No numerical values to classify.')+'<span><i style="background:#ddd"></i>No archived estimate</span>';transformMap();
 }catch(e){if(gen!==generation||mapGen!==mapGeneration||S.view!=='map')return;clearMap();$('map').innerHTML='<p class="empty">'+esc(e.message)+'</p>';}}

function mapContains(id){return S.geo.includes(id)||S.geo.includes(id.slice(0,2)+'*');}
bind('mapSelection',()=>{mapSelection=!mapSelection;$('mapSelection').setAttribute('aria-pressed',mapSelection);$('mapSelection').textContent=mapSelection?'Selection mode: on':'Select geographies';$('mapAction').hidden=true;renderMap();});
bind('mapAction',()=>{if(!mapFocus)return;const id=mapFocus.id;change(()=>{if(mapContains(id)){if(S.geo.includes(id.slice(0,2)+'*')){S.geo=S.geo.filter(g=>g!==id.slice(0,2)+'*');S.geo.push(...geographies.filter(g=>g.level==='county'&&g.state===id.slice(0,2)&&g.id!==id).map(g=>g.id));}S.geo=S.geo.filter(g=>g!==id);}else S.geo.push(id);S.geo=[...new Set(S.geo)];});});

function transformMap(){if($('mapShapes'))$('mapShapes').setAttribute('transform',`translate(${480+mapOffset[0]} ${235+mapOffset[1]}) scale(${mapZoom}) translate(-480 -235)`);}
$('searchForm').onsubmit=e=>{e.preventDefault();++suggestionGeneration;change(()=>{S.q=$('search').value.trim();S.table=/^[BC]\d{5}[A-Z]{0,3}$/i.test(S.q)?S.q.toUpperCase():'';resetTable();});};
$('search').oninput=async()=>{const id=++suggestionGeneration,term=$('search').value.trim();if(term.length<2){$('suggestions').innerHTML='';return;}try{const d=await fetchJSON('/api/catalog?'+new URLSearchParams({year:S.year,product:S.product,q:term,geo:S.geo.join(',')}));if(id!==suggestionGeneration)return;$('suggestions').innerHTML=d.slice(0,5).map(t=>`<button type="button" data-table="${t.id}">${esc(t.id+' — '+t.title)}<small> · ${esc(t.coverage.message)}</small></button>`).join('');$('suggestions').querySelectorAll('button').forEach(b=>b.onclick=()=>change(()=>{S.table=b.dataset.table;S.q=S.table;S.geo=[];resetTable('Suggested table opened with geography filters and table customizations cleared, following the archived search workflow.');}));}catch(e){if(id===suggestionGeneration)error(e);}};
$('product').onchange=()=>change(()=>{S.product=$('product').value;resetTable();stateNotice='Product changed. Table-specific filters, sorting, hidden items and map variable were cleared; geographies retained.';});$('year').onchange=()=>change(()=>{S.year=+$('year').value;resetTable();stateNotice='Year changed. Table-specific filters, sorting, hidden items and map variable were cleared; geographies retained.';});$('state').onchange=choices;
bind('applyGeo',()=>change(()=>{const st=$('state').value;S.geo=S.geo.filter(g=>!g.startsWith(st));S.geo.push(...[...$('geoChoices').querySelectorAll('input:checked')].map(x=>x.value));}));
bind('clearAll',()=>change(()=>{S=defaults();stateNotice='All selections and table customizations were reset.';}));bind('transpose',()=>change(()=>S.tp=!S.tp,false));$('moe').onchange=()=>change(()=>S.moe=$('moe').checked,false);bind('resetTable',()=>change(resetTable,false));
bind('customFilter',()=>{if(!result)return;modal('<h2>Custom Filter</h2><p>Keep geography rows whose estimate meets the condition. Filters apply to this table.</p><label for="filterVariable">Variable</label><select id="filterVariable">'+result.variables.map(v=>`<option value="${v.id}">${esc(v.id+' — '+v.label.replace('Estimate!!',''))}</option>`).join('')+'</select><label for="filterOperator">Condition</label><select id="filterOperator"><option value="ge">Greater than or equals</option><option value="gt">Greater than</option><option value="le">Less than or equals</option><option value="lt">Less than</option><option value="eq">Equals</option><option value="ne">Not equal</option></select><label for="filterValue">Value</label><input id="filterValue" type="number"><div class="dialog-actions"><button id="applyFilter">Apply</button><button id="clearFilters">Clear custom filters</button></div>');bind('applyFilter',()=>{if($('filterValue').value===''||!Number.isFinite(+$('filterValue').value)){error('Filter threshold must be a finite number');return;}$('modal').close();change(()=>S.filters.push({variable:$('filterVariable').value,op:$('filterOperator').value,value:$('filterValue').value}),false);});bind('clearFilters',()=>{$('modal').close();change(()=>S.filters=[],false);});});
bind('columns',()=>{if(!result)return;const items=S.tp?result.variables.map(v=>({id:v.id,name:v.label.replace('Estimate!!','')})):result.rows.map(r=>({id:r.id,name:r.name})),key=S.tp?'hidden':'hiddenGeo';modal('<h2>Hide / Show Columns</h2><p>Checked items are visible. Restore all to return to the full table.</p><div class="column-list">'+items.map(v=>`<label><input type="checkbox" value="${v.id}" ${S[key].includes(v.id)?'':'checked'}>${esc(v.name)}</label>`).join('')+'</div><div class="dialog-actions"><button id="applyColumns">Apply</button><button id="restoreColumns">Restore all</button></div>');bind('applyColumns',()=>{S[key]=[...$('modalBody').querySelectorAll('input:not(:checked)')].map(x=>x.value);$('modal').close();save();render();});bind('restoreColumns',()=>{$('modal').close();change(()=>{S.hidden=[];S.hiddenGeo=[];},false);});});
bind('download',()=>{if(!result)return;modal('<h2>Download Table</h2><p>'+esc(result.coverage.message)+'</p><p>Choose your download format.</p><label><input type="radio" name="format" value="csv" checked> CSV — customized view</label><label><input type="radio" name="format" value="xlsx"> Excel — customized view</label><label><input type="radio" name="format" value="zip"> ZIP — all archived selected geographies, full table and metadata</label><p>CSV and Excel include all rows in the customized view, including those outside the current scroll window. ZIP ignores custom filters and hidden columns. Unarchived data cannot be included.</p><button id="confirmDownload">Download</button>');bind('confirmDownload',()=>{const p=apiParams();p.set('format',$('modalBody').querySelector('input:checked').value);const a=document.createElement('a');a.href='/download?'+p;a.download='';a.click();$('modal').close();});});
for(const id of ['showMap','mapsView'])bind(id,()=>{if(result)change(()=>S.view='map',false);else error('Open a table and select geographies before viewing a map.');});for(const id of ['showTable','tablesView'])bind(id,()=>{if(result)change(()=>S.view='table',false);else location.href='/advanced';});$('mapVariable').onchange=()=>change(()=>S.mapVariable=$('mapVariable').value,false);bind('zoomIn',()=>{mapZoom=Math.min(8,mapZoom*1.4);transformMap();});bind('zoomOut',()=>{mapZoom=Math.max(.5,mapZoom/1.4);transformMap();});bind('mapReset',()=>{mapZoom=1;mapOffset=[0,0];transformMap();});let drag=null;$('map').onpointerdown=e=>{drag=[e.clientX,e.clientY,...mapOffset];};$('map').onpointermove=e=>{if(drag&&e.buttons){mapOffset=[drag[2]+e.clientX-drag[0],drag[3]+e.clientY-drag[1]];transformMap();}};$('map').onpointerup=()=>drag=null;
$('topics').innerHTML=['Income','Housing','Language','Internet','Age','Disability','Household'].map(t=>`<button class="link" data-topic="${t}">${t}</button><br>`).join('');$('topics').querySelectorAll('button').forEach(b=>b.onclick=()=>change(()=>{S.q=b.dataset.topic;S.table='';resetTable();}));
async function start(){const routeGen=++generation;++mapGeneration;++suggestionGeneration;result=null;stateNotice='';clearMap();$('tablePanel').hidden=true;$('results').replaceChildren();$('suggestions').replaceChildren();$('status').textContent='';S=decode();const portal=['/','/data.html'].includes(location.pathname),help=location.pathname==='/help';$('portal').hidden=!portal;$('workspace').hidden=portal||help;$('help').hidden=!help;if(help){const c=await fetchJSON('/api/coverage');if(routeGen!==generation)return;$('coverage').innerHTML='<table><thead><tr><th>Release</th><th>Table</th><th>Geographies</th><th>Variables</th></tr></thead><tbody>'+c.map(r=>`<tr><td>${r.year} ${r.product}</td><td>${r.table_id}</td><td>${r.geographies}</td><td>${r.variables}</td></tr>`).join('')+'</tbody></table>';}if(!portal&&!help)await refresh();}
window.onpopstate=()=>start().catch(error);start().catch(error);
