// Author-side UI verification. This does not expose evaluate/code execution to agents.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const fs=require('fs'),path=require('path'),assert=require('assert');
const out=process.env.WATEROFFICE_OUTPUT || '/tmp/wateroffice-workflows';fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH || '/opt/chrome-linux64/chrome',headless:true,chromiumSandbox:true});const context=await browser.newContext({viewport:{width:Number(process.env.VIEWPORT_WIDTH || 1440),height:Number(process.env.VIEWPORT_HEIGHT || 1000)},acceptDownloads:true});let page=await context.newPage(),records=[],errors=[];page.on('pageerror',e=>errors.push({url:page.url(),error:String(e),stack:e.stack}));const base=process.env.WATEROFFICE_ORIGIN||'http://wateroffice-web:8080';page.setDefaultTimeout(20000);
async function go(url){await page.goto(base+url,{waitUntil:'domcontentloaded'});await page.waitForTimeout(2000);const agree=page.locator('input[value="I Agree"]');if(await agree.count()){await agree.click();await page.waitForLoadState('domcontentloaded');await page.waitForTimeout(1500)}}
async function test(name,fn){if(process.env.TESTS&&!process.env.TESTS.split(",").includes(name))return;try{const priorErrors=errors.length;await fn();assert.equal(errors.length,priorErrors,JSON.stringify(errors.slice(priorErrors)));records.push({name,pass:true})}catch(e){records.push({name,pass:false,error:String(e)})}console.log(records.at(-1));try{await page.screenshot({path:path.join(out,name+'.png'),timeout:10000})}catch(e){records.at(-1).screenshotError=String(e)};fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({records,errors},null,2))}
await test('historical-graph-1948',async()=>{await go('/report/historical_e.html?stn=08EE004&mode=Graph&dataType=Daily&parameterType=Flow&first_year=1948&last_year=1948');await page.locator('#graph canvas').first().waitFor();assert.equal(await page.locator('#graph-settings input[name=first_year]').inputValue(),'1948');assert.equal(await page.locator('#graph-settings input[name=last_year]').inputValue(),'1948')});
await test('historical-table-download',async()=>{await go('/report/historical_e.html?stn=08EE004&mode=Table&dataType=Daily&parameterType=Flow&year=1948');assert((await page.locator('h1').innerText()).includes('QUICK'));await page.locator('a[href^="/download/index_e.html"]').first().click();const link=page.locator('a[href*="dt=dd"][href*="df=csv"]').first();const pending=page.waitForEvent('download');await link.click();const d=await pending;await d.saveAs(path.join(out,'quick.csv'));assert(fs.statSync(path.join(out,'quick.csv')).size>10000)});
await test('realtime-one-parameter',async()=>{await go('/report/real_time_e.html?stn=01AF002&mode=Table&startDate=2026-09-20&endDate=2026-09-21&prm1=47&prm2=-1');const table=page.locator('table.wb-tables').first();assert.equal(await table.locator('thead th').count(),5);assert((await table.locator('thead').innerText()).includes('Discharge'));assert.equal(await page.locator('#y1-type').inputValue(),'47');assert.equal(await page.locator('#y2-type').inputValue(),'-1');assert((await table.locator('tbody').innerText()).includes('2026-09-21'));});
await test('realtime-cross-tab-download',async()=>{const original=page;const href=await page.locator('a[href^="/download/index_e.html"]').first().getAttribute('href');page=await context.newPage();await go('/report/real_time_e.html?stn=08EE004&startDate=2026-09-23&endDate=2026-09-24');page=original;await go(href);const links=await page.locator('a[href^="/download/report_e.html"]').evaluateAll(es=>es.map(e=>e.href));assert(links.length);for(const link of links){const u=new URL(link);assert.equal(u.searchParams.get('stations'),'01AF002');assert.equal(u.searchParams.get('startDate'),'2026-09-20');assert.equal(u.searchParams.get('endDate'),'2026-09-21')}for(const p of context.pages())if(p!==original)await p.close()});
await test('realtime-graph',async()=>{await go('/report/real_time_e.html?stn=01AF002&mode=Graph&startDate=2026-09-20&endDate=2026-09-21&prm1=46&prm2=-1');await page.locator('canvas#graph').waitFor({timeout:15000});await page.waitForTimeout(1500);assert.equal(errors.length,0,errors.join('; '));assert(await page.locator('canvas#graph').evaluate(c=>{const d=c.getContext('2d').getImageData(0,0,c.width,c.height).data;return d.some((v,i)=>i%4===3&&v>0)}))});
await test('quick-list-create',async()=>{await go('/my_station_list/quick_graph_list/new_e.html');await page.locator('#list-name').fill('Workflow test');await page.locator('input[value=Save]').click();await page.waitForLoadState('domcontentloaded');await page.waitForTimeout(1500);assert((await page.locator('body').innerText()).includes('Workflow test'))});
await test('quick-list-graph',async()=>{await go('/my_station_list/quick_graph_list/parameters_e.html?id=first&station_number%5B%5D=01AF002');await page.locator('input[value="46"]').check();await page.locator('input[value="47"]').check();await page.locator('input[value=Save]').click();await page.waitForLoadState('domcontentloaded');await page.waitForTimeout(1500);await go('/my_station_list/index_e.html');await page.locator('.quick-graph canvas').first().waitFor({timeout:15000});assert.equal(await page.locator('.quick-graph').count(),1);assert.equal(await page.locator('[data-combined=true]').count(),1)});
await test('map-filter-url',async()=>{await go('/map/index_e.html?type=historical&station_name=BULKLEY');await page.waitForFunction(()=>document.querySelectorAll('.leaflet-marker-icon').length===6);assert((await page.locator('#no-stations').innerText()).startsWith('6 '));await page.locator('#station-name').fill('NONEXISTENT-ZZZ');assert((await page.locator('#no-stations').innerText()).startsWith('0 '));await page.reload({waitUntil:'domcontentloaded'});await page.waitForFunction(()=>document.querySelector('#no-stations')?.textContent.startsWith('0 '));assert.equal(await page.locator('#station-name').inputValue(),'NONEXISTENT-ZZZ');assert.equal(await page.locator('.leaflet-marker-icon').count(),0)});
await test('map-current-conditions',async()=>{await go('/map/index_e.html?type=real_time');await page.locator('.leaflet-marker-icon').first().waitFor();await page.locator('#current-conditions').click();await page.locator('input[name=current_conditions_markers]').evaluateAll(es=>es.forEach(e=>{e.checked=e.value==='ALL_TIME_HIGH';e.dispatchEvent(new Event('change',{bubbles:true}))}));assert((await page.locator('#no-stations').innerText()).startsWith('27 '));assert.equal(await page.locator('.leaflet-marker-icon').count(),27);await page.reload({waitUntil:'domcontentloaded'});await page.waitForFunction(()=>document.querySelectorAll('.leaflet-marker-icon').length===27)});
await test('cross-page-multiselect',async()=>{await go('/search/historical_results_e.html?search_type=province&province=NB');await page.locator('.dataTables_wrapper').waitFor();const first=page.locator('input[type=checkbox][name="check[]"]').first();const a=(await first.inputValue()).split(',')[0];await first.check();await page.locator('.paginate_button.next').first().click();const next=page.locator('input[type=checkbox][name="check[]"]').first();const b=(await next.inputValue()).split(',')[0];assert.notEqual(a,b);await next.check();await page.locator('input[name=view_report]').first().click();await page.waitForLoadState('domcontentloaded');const agree=page.locator('input[value="I Agree"]');if(await agree.count()){await agree.click();await page.waitForLoadState('domcontentloaded')}assert.deepEqual((await page.locator('#station option').evaluateAll(es=>es.map(e=>e.value))).sort(),[a,b].sort());await page.locator('main a[href*="mode=Table"]').first().click();await page.waitForLoadState('domcontentloaded');assert.equal(new URL(page.url()).searchParams.get('stations').split(',').length,2);assert.equal(await page.locator('#station option').count(),2);await page.locator('main a[href^="/download/index_e.html"]').first().click();await page.waitForLoadState('domcontentloaded');const href=await page.locator('a[href*="dt=dd"][href*="df=csv"]').first().getAttribute('href');assert.deepEqual(new URL(href,base).searchParams.get('stations').split(',').sort(),[a,b].sort())});
await test('realtime-mode-retains-query',async()=>{await go('/report/real_time_e.html?stn=01AF002&mode=Graph&startDate=2026-09-20&endDate=2026-09-21&prm1=47&prm2=-1&stations=01AF002,08EE004');await page.locator('main a[href*="mode=Table"]').first().click();await page.waitForLoadState('domcontentloaded');await page.locator('table.wb-tables').first().waitFor();const u=new URL(page.url());assert.equal(u.searchParams.get('prm1'),'47');assert.equal(u.searchParams.get('prm2'),'-1');assert.equal(u.searchParams.get('startDate'),'2026-09-20');assert.equal(await page.locator('#station option').count(),2);assert.equal(await page.locator('table.wb-tables').first().locator('thead th').count(),5)});

await test('historical-statistics-settings',async()=>{let responseBody;const capture=async r=>{if(r.url().includes('/services/historical_graph/'))responseBody=await r.json()};page.on('response',capture);await go('/report/historical_e.html?stn=08EE004&mode=Graph&dataType=Monthly&parameterType=Level&first_year=2020&last_year=2020&mean1=1&upper1=1&start_year=1946&end_year=1950');await page.locator('#graph canvas').first().waitFor();assert(await page.locator('#mean').isChecked());assert(await page.locator('#upper-quartile').isChecked());assert.equal(await page.locator('#start-year').inputValue(),'1946');assert.equal(await page.locator('#offline-query-error').count(),0);const values=responseBody;page.off('response',capture);assert.equal(values.mean.length,12);assert.equal(values.mean[1][1],'.864');assert.equal(values.upper_quartile.length,12);await page.locator('main a[href*="mode=Table"]').first().click();await page.waitForLoadState('domcontentloaded');await page.locator('main a[href*="mode=Graph"]').first().click();await page.waitForLoadState('domcontentloaded');assert(await page.locator('#upper-quartile').isChecked());assert.equal(await page.locator('#end-year').inputValue(),'1950')});
await test('remarks-navigation',async()=>{await go('/report/historical_e.html?stn=08FE002&mode=Graph&dataType=Daily&parameterType=Flow&first_year=2020&last_year=2020');await page.locator('a[href*="/report/remarks_e.html"]').click();await page.waitForLoadState('domcontentloaded');assert((await page.locator('h1').innerText()).includes('KEMANO'));assert((await page.locator('main table').innerText()).includes('ALCAN ALUMINUM'));await page.locator('a', {hasText:/^Report$/}).click();await page.waitForLoadState('domcontentloaded');assert.equal(new URL(page.url()).searchParams.get('stn'),'08FE002');assert.equal(new URL(page.url()).searchParams.get('first_year'),'2020')});

await test('map-popup-basin',async()=>{await go('/map/index_e.html?type=historical&target_station=02AA001');await page.locator('.leaflet-marker-icon').waitFor();const basin=page.waitForResponse(r=>r.url().includes('/data/map/geojson/basin_02_'));await page.locator('.leaflet-marker-icon').click();assert.equal((await basin).status(),200);await page.waitForTimeout(1000);assert((await page.locator('#popup').innerText()).includes('PIGEON RIVER'));await page.locator('#basin-display').click();assert.equal(await page.locator('#basin-display').getAttribute('data-state'),'show');assert(await page.locator('#basin-transparency').isEnabled());await page.locator('#basin-transparency').fill('0.7');await page.locator('#basin-transparency').dispatchEvent('input');assert.equal(await page.locator('.transparency-value').innerText(),'70%');await page.screenshot({path:path.join(out,'map-popup-basin-visible.png')});await page.locator('#popup-close').click();assert.equal(await page.locator('#popup').count(),0);await page.locator('#station-id').fill('NONEXISTENT');assert.equal(await page.locator('.leaflet-marker-icon').count(),0)});

await test('realtime-station-timezone',async()=>{await go('/report/real_time_e.html?stn=08EE004&mode=Table&startDate=2026-09-20&endDate=2026-09-21&prm1=46&prm2=-1');assert.equal(await page.locator('main table thead th').first().innerText(),'Date (PST)');assert((await page.locator('h1').innerText()).includes('BULKLEY'))});
await test('realtime-search-combination',async()=>{await go('/search/real_time_e.html');await page.locator('#province').selectOption('BC');await page.locator('#province-search').check();await page.locator('#parameter-type').selectOption('46');await page.locator('#regulation').selectOption('N');await page.locator('main input[type=submit]').first().click();await page.waitForLoadState('domcontentloaded');assert((await page.locator('main').innerText()).includes('Found 288 stations'));await page.reload({waitUntil:'domcontentloaded'});assert((await page.locator('main').innerText()).includes('Found 288 stations'))});
await test('watch-list-add-delete',async()=>{await go('/my_station_list/watch_list_custom_e.html?search_type=province&province=NB');await page.locator('input[type=search]').last().fill('GRAND FALLS');await page.locator('input[name="id[]"][value="01AF002"]').check();await page.locator('input[name=add]').first().click();await page.waitForLoadState('domcontentloaded');await go('/my_station_list/index_e.html');assert((await page.locator('.watch-list').innerText()).includes('01AF002'));await page.reload({waitUntil:'domcontentloaded'});assert.equal(await page.locator('.watch-list').count(),1);await page.locator('a[href="/my_station_list/watch_list_custom_e.html"]').click();await page.waitForLoadState('domcontentloaded');await page.locator('#watch_list_table input[type=checkbox]').check();await page.locator('input[name=remove]').click();await page.waitForLoadState('domcontentloaded');await go('/my_station_list/index_e.html');assert((await page.locator('main').innerText()).includes('No watch list is available'))});
await test('historical-history-tabs',async()=>{await go('/report/historical_e.html?stn=08EE004&mode=Graph&dataType=Daily&parameterType=Flow&first_year=1948&last_year=1948');await go('/report/historical_e.html?stn=01AD003&mode=Graph&dataType=Daily&parameterType=Level&first_year=2020&last_year=2020');await page.goBack({waitUntil:'domcontentloaded'});assert.equal(await page.locator('#station').inputValue(),'08EE004');assert.equal(await page.locator('#first-year').inputValue(),'1948');await page.goForward({waitUntil:'domcontentloaded'});assert.equal(await page.locator('#station').inputValue(),'01AD003');const first=page;page=await context.newPage();await go('/report/historical_e.html?stn=08EE004&mode=Table&dataType=Daily&parameterType=Flow&year=1950');page=first;await page.reload({waitUntil:'domcontentloaded'});assert.equal(await page.locator('#station').inputValue(),'01AD003');assert.equal(await page.locator('#parameter-type').inputValue(),'Level');for(const p of context.pages())if(p!==first)await p.close()});

await test('annual-extremes-modes',async()=>{await go('/report/historical_e.html?stn=08EE004&mode=Graph&dataType=Annual%20Extremes&parameterType=Flow');await page.locator('#graph canvas').first().waitFor();assert((await page.locator('h1').innerText()).includes('Annual Maximum'));assert.equal(await page.locator('#offline-query-error').count(),0);await page.locator('main a[href*="mode=Table"]').first().click();await page.waitForLoadState('domcontentloaded');assert((await page.locator('main table').first().innerText()).includes('2007-06-08'));await page.locator('#data-type').selectOption('Peak');await page.locator('#apply').click();await page.waitForLoadState('domcontentloaded');assert((await page.locator('h1').innerText()).includes('Instantaneous'));assert((await page.locator('main table').first().innerText()).includes('2002-06-16 20:00'));await page.locator('main a[href*="mode=Graph"]').first().click();await page.waitForLoadState('domcontentloaded');await page.locator('#graph canvas').first().waitFor();assert.equal(await page.locator('#offline-query-error').count(),0)});
await test('map-popup-drag-stale',async()=>{
 await go('/map/index_e.html?type=historical&target_station=02AA001');await page.locator('.leaflet-marker-icon').waitFor();
 let release;const delay=new Promise(r=>release=r);let entered;const arrival=new Promise(r=>entered=r);
 await page.route('**/data/map/geojson/basin_02_simplified.json',async route=>{const response=await route.fetch();entered();await delay;await route.fulfill({response})});
 await page.locator('.leaflet-marker-icon').click();await arrival;
 const header=page.locator('#popup .popup-header');await header.scrollIntoViewIfNeeded();const before=await header.boundingBox();await page.mouse.move(before.x+30,before.y+10);await page.mouse.down();await page.mouse.move(before.x+110,before.y+60);await page.mouse.up();const after=await header.boundingBox();
 // Original mobile CSS makes the popup full-width; dragging must keep it on screen.
 if(before.width<page.viewportSize().width-40)assert(Math.abs(after.x-before.x)>20);
 else{const box=await page.locator('#popup').boundingBox();assert(box.x>=-1&&box.x+box.width<=page.viewportSize().width+1)}
 await page.locator('#popup-close').click();release();await page.waitForTimeout(1800);assert.equal(await page.locator('#popup').count(),0);assert.equal(await page.locator('.leaflet-overlay-pane path').count(),0);await page.unroute('**/data/map/geojson/basin_02_simplified.json');
});
await test('realtime-daily-mixed',async()=>{
 await go('/report/real_time_e.html?stn=08EE004&mode=Table&startDate=2026-09-23&endDate=2026-09-24&prm1=3&prm2=6');
 const table=page.locator('table.wb-tables').first();assert.equal(await table.locator('thead th').count(),3);assert((await table.innerText()).includes('0.355'));assert((await table.innerText()).includes('71.7'));
 await page.locator('main a[href*="mode=Graph"]').first().click();await page.waitForLoadState('domcontentloaded');await page.locator('canvas#graph').waitFor();assert.equal(await page.locator('#offline-query-error').count(),0);
 await go('/report/real_time_e.html?stn=08EE004&mode=Table&startDate=2026-09-23&endDate=2026-09-23&prm1=3&prm2=47');assert.equal(await page.locator('table.wb-tables').first().locator('thead th').count(),6);assert((await page.locator('.dataTables_info').first().innerText()).includes('288'));
});
await test('realtime-spatial-metadata',async()=>{
 await go('/search/real_time_e.html');for(const name of ['RIVIÈRE','A (B)/C \"D\"']){await page.locator('#station-name').fill(name);assert(await page.locator('#station-name').evaluate(e=>e.checkValidity()))}await page.locator('#station-name').fill('<invalid>');assert(!(await page.locator('#station-name').evaluate(e=>e.checkValidity())));await page.locator('#station-name').fill('BULKLEY');await page.locator('#gross-drainage-area').fill('7341');await page.locator('#gross-drainage-operator').selectOption('<=');await page.locator('main input[type=submit]').first().click();await page.waitForLoadState('domcontentloaded');assert((await page.locator('main').innerText()).includes('Found 2 stations'));assert((await page.locator('main').innerText()).includes('08EE004'));await page.locator('a[href="/report/real_time_e.html?stn=08EE004"]').click();await page.waitForLoadState('domcontentloaded');const agree=page.locator('input[value="I Agree"]');if(await agree.count()){await agree.click();await page.waitForLoadState('domcontentloaded')};assert.equal(await page.locator('[aria-labelledby="gross-drainage"]').innerText(),'7,341 km2');assert.equal(await page.locator('[aria-labelledby="record-length"]').innerText(),'97 Years');assert((await page.locator('[aria-labelledby="latitude"]').innerText()).includes('54°'));await page.screenshot({path:path.join(out,'realtime-metadata-full.png'),fullPage:true});
});
await test('map-complete-download',async()=>{
 for(const type of ['historical','real_time']){
 await go('/map/index_e.html?type='+type);await page.locator('#station-name').fill('BULKLEY');await page.waitForTimeout(1000);const pending=page.waitForEvent('download');await page.locator('#download').click();const d=await pending;await d.saveAs(path.join(out,'map-'+type+'.csv'));const body=fs.readFileSync(path.join(out,'map-'+type+'.csv'),'utf8');assert(body.includes('Operating Agency'));assert.equal(body.trim().split('\n').length,type==='historical'?7:4);
 }
});
await test('watch-snapshot-pagination',async()=>{
 await go('/my_station_list/watch_list_custom_e.html?search_type=province&province=NB');const boxes=page.locator('#watch_results_table input[name="id[]"]');assert((await boxes.count())>=6);for(let i=0;i<6;i++)await boxes.nth(i).check();await page.locator('input[name=add]').first().click();await page.waitForLoadState('domcontentloaded');await go('/my_station_list/index_e.html');assert.equal(await page.locator('.watch-list').count(),5);assert((await page.locator('main').innerText()).includes('Published Watch List summaries'));const firstTitle=await page.locator('.watch-list h3').first().innerText();assert(await page.locator('.watch-list img').count());assert(await page.locator('.watch-list img').evaluateAll(es=>es.every(e=>e.complete&&e.naturalWidth>0)));await page.locator('a[href*="watch_page=1"]').click();await page.waitForLoadState('domcontentloaded');assert.equal(await page.locator('.watch-list').count(),1);await page.reload({waitUntil:'domcontentloaded'});assert.equal(await page.locator('.watch-list').count(),1);await page.locator('a[href*="watch_page=0"]').click();await page.waitForLoadState('domcontentloaded');assert.equal(await page.locator('.watch-list h3').first().innerText(),firstTitle);
});
await test('realtime-live-state-links',async()=>{
 await go('/report/real_time_e.html?stn=08EE004&mode=Graph&prm1=46&prm2=-1&startDate=2026-09-23&endDate=2026-09-24');await page.locator('#y1-type').selectOption('3');await page.waitForTimeout(600);assert.equal(new URL(page.url()).searchParams.get('prm1'),'3');const tableLink=page.locator('main a[href*="mode=Table"]').first();assert.equal(new URL(await tableLink.getAttribute('href'),base).searchParams.get('prm1'),'3');await tableLink.click();await page.waitForLoadState('domcontentloaded');assert((await page.locator('main table thead').first().innerText()).includes('daily mean'));await page.goBack({waitUntil:'domcontentloaded'});await page.waitForTimeout(500);assert.equal(await page.locator('#y1-type').inputValue(),'3');await page.goBack({waitUntil:'domcontentloaded'});await page.waitForTimeout(500);assert.equal(await page.locator('#y1-type').inputValue(),'46');await page.locator('#start-date').fill('2026-09-24');await page.locator('#start-date').dispatchEvent('change');await page.waitForTimeout(600);const copied=page.url();await page.reload({waitUntil:'domcontentloaded'});assert.equal(await page.locator('#start-date').inputValue(),'2026-09-24');const dl=await page.locator('a[href^="/download/index_e.html"]').first().getAttribute('href');assert.equal(new URL(dl,base).searchParams.get('startDate'),'2026-09-24');const other=await context.newPage();await other.goto(copied,{waitUntil:'domcontentloaded'});assert.equal(await other.locator('#start-date').inputValue(),'2026-09-24');await other.close();
});
await test('quick-list-parameter-edit',async()=>{
 await go('/my_station_list/quick_graph_list/edit_e.html?id=first');assert.equal(await page.locator('#watch_list_table tbody tr').count(),2);
 await page.locator('#param01AF00246').check();await page.locator('input[value="Edit Parameters"]').click();await page.waitForLoadState('domcontentloaded');assert(await page.locator('input[value="46"]').isDisabled());assert(await page.locator('input[value="47"]').isChecked());await page.locator('input[value="3"]').check();await page.locator('input[value="Save"]').click();await page.waitForLoadState('domcontentloaded');assert.equal(await page.locator('#watch_list_table tbody tr').count(),3);
 await page.locator('#param01AF00247').check();await page.locator('input[value="Delete Parameters"]').click();await page.waitForLoadState('domcontentloaded');assert((await page.locator('main').innerText()).includes('Are you sure'));await page.locator('input[value="Yes"]').click();await page.waitForURL('**/quick_graph_list/edit_e.html?*');await page.locator('#watch_list_table tbody tr').first().waitFor();assert.equal(await page.locator('#watch_list_table tbody tr').count(),2);assert.equal(await page.locator('#param01AF00247').count(),0);assert.equal(await page.locator('#param01AF00246').count(),1);
 await go('/my_station_list/quick_graph_list/edit_e.html?id=first&search_type=province&province=NB');assert.equal(await page.locator('#watch_list_table tbody tr').count(),2);assert((await page.locator('table').count())>=2);
 await go('/my_station_list/quick_graph_list/configure_e.html');await page.locator('input[value="Rename"]').click();await page.waitForLoadState('domcontentloaded');await page.locator('#list-name').fill('Renamed "A"');await page.locator('input[value="Save"]').click();await page.waitForLoadState('domcontentloaded');assert.equal(await page.locator('#list option:checked').innerText(),'Renamed "A"');await go('/my_station_list/index_e.html');assert.equal(await page.locator('.quick-graph').count(),2);
});
await test('quick-list-delete-confirmation',async()=>{
 await go('/my_station_list/quick_graph_list/configure_e.html');await page.locator('input[value="Delete"]').click();await page.waitForLoadState('domcontentloaded');assert((await page.locator('main').innerText()).includes('Are you sure'));await page.locator('main a').filter({hasText:/^No$/}).click();await page.waitForLoadState('domcontentloaded');assert.equal(await page.locator('#list option').count(),1);await page.locator('input[value="Delete"]').click();await page.waitForLoadState('domcontentloaded');await page.locator('input[value="Yes"]').click();await page.waitForURL('**/quick_graph_list/configure_e.html');await go('/my_station_list/index_e.html');assert((await page.locator('main').innerText()).includes('No quick graph list is available'));
});
await test('datum-navigation',async()=>{
 await go('/report/historical_e.html?stn=08EE004&mode=Table&dataType=Daily&parameterType=Flow&year=1948');
 await page.locator('[aria-labelledby="datum-data"] a').click();await page.waitForLoadState('domcontentloaded');assert((await page.locator('main').innerText()).includes('523.337'));assert((await page.locator('main').innerText()).includes('0.008'));
 const reportLink=page.locator('#wb-bc a').filter({hasText:'Report'});assert((await reportLink.getAttribute('href')).includes('/report/real_time_e.html?'));assert((await reportLink.getAttribute('href')).includes('mode=Table'));
 await page.locator('a[href="/report/datum_faq_e.html"]').click();await page.waitForLoadState('domcontentloaded');assert((await page.locator('h1').innerText()).includes('Frequently Asked Questions'));const diagram=page.locator('img[src="/images/datum_en.jpg"]');assert(await diagram.evaluate(e=>e.complete&&e.naturalWidth>0));
 await page.goBack({waitUntil:'domcontentloaded'});assert((await page.locator('h1').innerText()).includes('08EE004'));await page.reload({waitUntil:'domcontentloaded'});assert((await page.locator('main').innerText()).includes('523.337'));
 await go('/report/real_time_e.html?stn=01AF002&mode=Table&startDate=2026-09-23&endDate=2026-09-24');await page.locator('[aria-labelledby="datum-data"] a').click();await page.waitForLoadState('domcontentloaded');assert((await page.locator('h1').innerText()).includes('01AF002'));assert(!(await page.locator('main').innerText()).includes('08EE004'));
 const bad=await context.request.get(base+'/report/datum_e.html?stn=../../author');assert.equal(bad.status(),400);
});
await test('new-session-empty' ,async()=>{const fresh=await browser.newContext();page=await fresh.newPage();await go('/my_station_list/index_e.html');assert((await page.locator('body').innerText()).includes('No quick graph list is available'));await fresh.close();page=context.pages()[0]});
await browser.close();process.exitCode=records.some(r=>!r.pass)?1:0;})();
